# Configurações para o perfil 'docker'
# src/main/resources/application-docker.properties

server.port=8080

# Aponta para o contêiner do MongoDB usando o nome do serviço 'mongo-db'
spring.data.mongodb.uri=mongodb://root:password@mongo-db:27017/keeplite?authSource=admin

# Aponta para o contêiner do Redis usando o nome do serviço 'redis-cache'
spring.data.redis.host=redis-cache
spring.data.redis.port=6379
spring.data.redis.password=yourpassword

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=86400000

# Credenciais do Admin Semente
admin.email=admin@keeplite.com
admin.password=password