# Configurações para o perfil de desenvolvimento local ('dev')
# src/main/resources/application-dev.properties

server.port=8081

# Aponta para o MongoDB via a porta exposta na sua máquina (localhost)
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/keeplite?authSource=admin

# Aponta para o Redis via a porta exposta na sua máquina (localhost)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redispassword

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token-expiration-ms=3600000
jwt.refresh-token-expiration-ms=86400000

# Credenciais do Admin Semente
admin.email=admin@keeplite.com
admin.password=password
