spring.application.name=keep-lite

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Expõe apenas o endpoint 'health' via HTTP. Todos os outros ficam desabilitados.
management.endpoints.web.exposure.include=health
